[package]
name = "cochavira_core"
version = "0.0.1"
edition = "2024"

[dependencies]
wgpu = { version = "0.19", optional = true }
pollster = { version = "0.3", optional = true }

[features]
default = []
gpu = ["wgpu", "pollster"]
cpu = []

[dev-dependencies]
pollster = "0.3"