[package]
name = "cochavira_core"
version = "0.0.1"
edition = "2024"

[dependencies]
wgpu = { version = "0.19" }
pollster = { version = "0.3" }
sv-parser = "0.13.4"
tempfile = "3"
tree-sitter = "0.26.3"
tree-sitter-systemverilog = "0.3.1"

[features]
default = []